# Generated by Django 6.0.4 on 2026-04-11 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhongTro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=200)),
                ('mo_ta', models.TextField()),
                ('gia_thue', models.IntegerField()),
                ('dien_tich', models.FloatField()),
                ('dia_chi', models.CharField(max_length=255)),
                ('so_dien_thoai', models.CharField(max_length=15)),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='phongtro/')),
                ('ngay_dang', models.DateTimeField(auto_now_add=True)),
                ('chu_tro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
