# Generated by Django 6.0.4 on 2026-04-11 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhachLienHe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_khach', models.CharField(max_length=100)),
                ('so_dien_thoai', models.CharField(max_length=15)),
                ('noi_dung', models.TextField()),
                ('ngay_gui', models.DateTimeField(auto_now_add=True)),
                ('phong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanly.phongtro')),
            ],
        ),
    ]
