# Generated by Django 6.0.4 on 2026-04-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0002_khachlienhe'),
    ]

    operations = [
        migrations.AddField(
            model_name='phongtro',
            name='khu_vuc',
            field=models.CharField(choices=[('Hà Nội', 'Hà Nội'), ('TPHCM', 'TPHCM'), ('Đà Nẵng', 'Đà Nẵng'), ('Kiên Giang', 'Kiên Giang'), ('Thái Bình', 'Thái Bình'), ('Hải Phòng', 'Hải Phòng')], default='Hà Nội', max_length=50),
        ),
    ]
